"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bungie-api-ts
 * Do not edit these files manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var ContentPropertyDataTypeEnum;
(function (ContentPropertyDataTypeEnum) {
    ContentPropertyDataTypeEnum[ContentPropertyDataTypeEnum["None"] = 0] = "None";
    ContentPropertyDataTypeEnum[ContentPropertyDataTypeEnum["Plaintext"] = 1] = "Plaintext";
    ContentPropertyDataTypeEnum[ContentPropertyDataTypeEnum["Html"] = 2] = "Html";
    ContentPropertyDataTypeEnum[ContentPropertyDataTypeEnum["Dropdown"] = 3] = "Dropdown";
    ContentPropertyDataTypeEnum[ContentPropertyDataTypeEnum["List"] = 4] = "List";
    ContentPropertyDataTypeEnum[ContentPropertyDataTypeEnum["Json"] = 5] = "Json";
    ContentPropertyDataTypeEnum[ContentPropertyDataTypeEnum["Content"] = 6] = "Content";
    ContentPropertyDataTypeEnum[ContentPropertyDataTypeEnum["Representation"] = 7] = "Representation";
    ContentPropertyDataTypeEnum[ContentPropertyDataTypeEnum["Set"] = 8] = "Set";
    ContentPropertyDataTypeEnum[ContentPropertyDataTypeEnum["File"] = 9] = "File";
    ContentPropertyDataTypeEnum[ContentPropertyDataTypeEnum["FolderSet"] = 10] = "FolderSet";
    ContentPropertyDataTypeEnum[ContentPropertyDataTypeEnum["Date"] = 11] = "Date";
    ContentPropertyDataTypeEnum[ContentPropertyDataTypeEnum["MultilinePlaintext"] = 12] = "MultilinePlaintext";
    ContentPropertyDataTypeEnum[ContentPropertyDataTypeEnum["DestinyContent"] = 13] = "DestinyContent";
    ContentPropertyDataTypeEnum[ContentPropertyDataTypeEnum["Color"] = 14] = "Color";
})(ContentPropertyDataTypeEnum = exports.ContentPropertyDataTypeEnum || (exports.ContentPropertyDataTypeEnum = {}));
