"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bungie-api-ts
 * Do not edit these files manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var CommunityStatusSort;
(function (CommunityStatusSort) {
    CommunityStatusSort[CommunityStatusSort["Viewers"] = 0] = "Viewers";
    CommunityStatusSort[CommunityStatusSort["Trending"] = 1] = "Trending";
    CommunityStatusSort[CommunityStatusSort["OverallViewers"] = 2] = "OverallViewers";
    CommunityStatusSort[CommunityStatusSort["Followers"] = 3] = "Followers";
})(CommunityStatusSort = exports.CommunityStatusSort || (exports.CommunityStatusSort = {}));
