"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bungie-api-ts
 * Do not edit these files manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * This enum represents a set of flags - use bitwise operators to check which of
 * these match your value.
 */
var ForumTopicsCategoryFiltersEnum;
(function (ForumTopicsCategoryFiltersEnum) {
    ForumTopicsCategoryFiltersEnum[ForumTopicsCategoryFiltersEnum["None"] = 0] = "None";
    ForumTopicsCategoryFiltersEnum[ForumTopicsCategoryFiltersEnum["Links"] = 1] = "Links";
    ForumTopicsCategoryFiltersEnum[ForumTopicsCategoryFiltersEnum["Questions"] = 2] = "Questions";
    ForumTopicsCategoryFiltersEnum[ForumTopicsCategoryFiltersEnum["AnsweredQuestions"] = 4] = "AnsweredQuestions";
    ForumTopicsCategoryFiltersEnum[ForumTopicsCategoryFiltersEnum["Media"] = 8] = "Media";
    ForumTopicsCategoryFiltersEnum[ForumTopicsCategoryFiltersEnum["TextOnly"] = 16] = "TextOnly";
    ForumTopicsCategoryFiltersEnum[ForumTopicsCategoryFiltersEnum["Announcement"] = 32] = "Announcement";
    ForumTopicsCategoryFiltersEnum[ForumTopicsCategoryFiltersEnum["BungieOfficial"] = 64] = "BungieOfficial";
    ForumTopicsCategoryFiltersEnum[ForumTopicsCategoryFiltersEnum["Polls"] = 128] = "Polls";
})(ForumTopicsCategoryFiltersEnum = exports.ForumTopicsCategoryFiltersEnum || (exports.ForumTopicsCategoryFiltersEnum = {}));
var ForumTopicsQuickDateEnum;
(function (ForumTopicsQuickDateEnum) {
    ForumTopicsQuickDateEnum[ForumTopicsQuickDateEnum["All"] = 0] = "All";
    ForumTopicsQuickDateEnum[ForumTopicsQuickDateEnum["LastYear"] = 1] = "LastYear";
    ForumTopicsQuickDateEnum[ForumTopicsQuickDateEnum["LastMonth"] = 2] = "LastMonth";
    ForumTopicsQuickDateEnum[ForumTopicsQuickDateEnum["LastWeek"] = 3] = "LastWeek";
    ForumTopicsQuickDateEnum[ForumTopicsQuickDateEnum["LastDay"] = 4] = "LastDay";
})(ForumTopicsQuickDateEnum = exports.ForumTopicsQuickDateEnum || (exports.ForumTopicsQuickDateEnum = {}));
var ForumTopicsSortEnum;
(function (ForumTopicsSortEnum) {
    ForumTopicsSortEnum[ForumTopicsSortEnum["Default"] = 0] = "Default";
    ForumTopicsSortEnum[ForumTopicsSortEnum["LastReplied"] = 1] = "LastReplied";
    ForumTopicsSortEnum[ForumTopicsSortEnum["MostReplied"] = 2] = "MostReplied";
    ForumTopicsSortEnum[ForumTopicsSortEnum["Popularity"] = 3] = "Popularity";
    ForumTopicsSortEnum[ForumTopicsSortEnum["Controversiality"] = 4] = "Controversiality";
    ForumTopicsSortEnum[ForumTopicsSortEnum["Liked"] = 5] = "Liked";
    ForumTopicsSortEnum[ForumTopicsSortEnum["HighestRated"] = 6] = "HighestRated";
    ForumTopicsSortEnum[ForumTopicsSortEnum["MostUpvoted"] = 7] = "MostUpvoted";
})(ForumTopicsSortEnum = exports.ForumTopicsSortEnum || (exports.ForumTopicsSortEnum = {}));
var ForumPostSortEnum;
(function (ForumPostSortEnum) {
    ForumPostSortEnum[ForumPostSortEnum["Default"] = 0] = "Default";
    ForumPostSortEnum[ForumPostSortEnum["OldestFirst"] = 1] = "OldestFirst";
})(ForumPostSortEnum = exports.ForumPostSortEnum || (exports.ForumPostSortEnum = {}));
var ForumMediaType;
(function (ForumMediaType) {
    ForumMediaType[ForumMediaType["None"] = 0] = "None";
    ForumMediaType[ForumMediaType["Image"] = 1] = "Image";
    ForumMediaType[ForumMediaType["Video"] = 2] = "Video";
    ForumMediaType[ForumMediaType["Youtube"] = 3] = "Youtube";
})(ForumMediaType = exports.ForumMediaType || (exports.ForumMediaType = {}));
var ForumPostPopularity;
(function (ForumPostPopularity) {
    ForumPostPopularity[ForumPostPopularity["Empty"] = 0] = "Empty";
    ForumPostPopularity[ForumPostPopularity["Default"] = 1] = "Default";
    ForumPostPopularity[ForumPostPopularity["Discussed"] = 2] = "Discussed";
    ForumPostPopularity[ForumPostPopularity["CoolStory"] = 3] = "CoolStory";
    ForumPostPopularity[ForumPostPopularity["HeatingUp"] = 4] = "HeatingUp";
    ForumPostPopularity[ForumPostPopularity["Hot"] = 5] = "Hot";
})(ForumPostPopularity = exports.ForumPostPopularity || (exports.ForumPostPopularity = {}));
var ForumRecruitmentIntensityLabel;
(function (ForumRecruitmentIntensityLabel) {
    ForumRecruitmentIntensityLabel[ForumRecruitmentIntensityLabel["None"] = 0] = "None";
    ForumRecruitmentIntensityLabel[ForumRecruitmentIntensityLabel["Casual"] = 1] = "Casual";
    ForumRecruitmentIntensityLabel[ForumRecruitmentIntensityLabel["Professional"] = 2] = "Professional";
})(ForumRecruitmentIntensityLabel = exports.ForumRecruitmentIntensityLabel || (exports.ForumRecruitmentIntensityLabel = {}));
var ForumRecruitmentToneLabel;
(function (ForumRecruitmentToneLabel) {
    ForumRecruitmentToneLabel[ForumRecruitmentToneLabel["None"] = 0] = "None";
    ForumRecruitmentToneLabel[ForumRecruitmentToneLabel["FamilyFriendly"] = 1] = "FamilyFriendly";
    ForumRecruitmentToneLabel[ForumRecruitmentToneLabel["Rowdy"] = 2] = "Rowdy";
})(ForumRecruitmentToneLabel = exports.ForumRecruitmentToneLabel || (exports.ForumRecruitmentToneLabel = {}));
var CommunityContentSortMode;
(function (CommunityContentSortMode) {
    CommunityContentSortMode[CommunityContentSortMode["Trending"] = 0] = "Trending";
    CommunityContentSortMode[CommunityContentSortMode["Latest"] = 1] = "Latest";
    CommunityContentSortMode[CommunityContentSortMode["HighestRated"] = 2] = "HighestRated";
})(CommunityContentSortMode = exports.CommunityContentSortMode || (exports.CommunityContentSortMode = {}));
