"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bungie-api-ts
 * Do not edit these files manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var FireteamActivityType;
(function (FireteamActivityType) {
    FireteamActivityType[FireteamActivityType["All"] = 0] = "All";
    FireteamActivityType[FireteamActivityType["Raid"] = 1] = "Raid";
    FireteamActivityType[FireteamActivityType["Crucible"] = 2] = "Crucible";
    FireteamActivityType[FireteamActivityType["Trials"] = 3] = "Trials";
    FireteamActivityType[FireteamActivityType["Nightfall"] = 4] = "Nightfall";
    FireteamActivityType[FireteamActivityType["Anything"] = 5] = "Anything";
    FireteamActivityType[FireteamActivityType["Gambit"] = 6] = "Gambit";
    FireteamActivityType[FireteamActivityType["BlindWell"] = 7] = "BlindWell";
    FireteamActivityType[FireteamActivityType["EscalationProtocol"] = 8] = "EscalationProtocol";
    FireteamActivityType[FireteamActivityType["Forge"] = 9] = "Forge";
    FireteamActivityType[FireteamActivityType["Reckoning"] = 10] = "Reckoning";
    FireteamActivityType[FireteamActivityType["Menagerie"] = 11] = "Menagerie";
    FireteamActivityType[FireteamActivityType["NightmareHunts"] = 12] = "NightmareHunts";
    FireteamActivityType[FireteamActivityType["VexOffensive"] = 13] = "VexOffensive";
    FireteamActivityType[FireteamActivityType["AltarsOfSorrow"] = 14] = "AltarsOfSorrow";
    FireteamActivityType[FireteamActivityType["Dungeon"] = 15] = "Dungeon";
})(FireteamActivityType = exports.FireteamActivityType || (exports.FireteamActivityType = {}));
var FireteamDateRange;
(function (FireteamDateRange) {
    FireteamDateRange[FireteamDateRange["All"] = 0] = "All";
    FireteamDateRange[FireteamDateRange["Now"] = 1] = "Now";
    FireteamDateRange[FireteamDateRange["TwentyFourHours"] = 2] = "TwentyFourHours";
    FireteamDateRange[FireteamDateRange["FortyEightHours"] = 3] = "FortyEightHours";
    FireteamDateRange[FireteamDateRange["ThisWeek"] = 4] = "ThisWeek";
})(FireteamDateRange = exports.FireteamDateRange || (exports.FireteamDateRange = {}));
var FireteamPlatform;
(function (FireteamPlatform) {
    FireteamPlatform[FireteamPlatform["Unknown"] = 0] = "Unknown";
    FireteamPlatform[FireteamPlatform["Playstation4"] = 1] = "Playstation4";
    FireteamPlatform[FireteamPlatform["XboxOne"] = 2] = "XboxOne";
    FireteamPlatform[FireteamPlatform["Blizzard"] = 3] = "Blizzard";
    FireteamPlatform[FireteamPlatform["Steam"] = 4] = "Steam";
})(FireteamPlatform = exports.FireteamPlatform || (exports.FireteamPlatform = {}));
var FireteamPublicSearchOption;
(function (FireteamPublicSearchOption) {
    FireteamPublicSearchOption[FireteamPublicSearchOption["PublicAndPrivate"] = 0] = "PublicAndPrivate";
    FireteamPublicSearchOption[FireteamPublicSearchOption["PublicOnly"] = 1] = "PublicOnly";
    FireteamPublicSearchOption[FireteamPublicSearchOption["PrivateOnly"] = 2] = "PrivateOnly";
})(FireteamPublicSearchOption = exports.FireteamPublicSearchOption || (exports.FireteamPublicSearchOption = {}));
var FireteamSlotSearch;
(function (FireteamSlotSearch) {
    FireteamSlotSearch[FireteamSlotSearch["NoSlotRestriction"] = 0] = "NoSlotRestriction";
    FireteamSlotSearch[FireteamSlotSearch["HasOpenPlayerSlots"] = 1] = "HasOpenPlayerSlots";
    FireteamSlotSearch[FireteamSlotSearch["HasOpenPlayerOrAltSlots"] = 2] = "HasOpenPlayerOrAltSlots";
})(FireteamSlotSearch = exports.FireteamSlotSearch || (exports.FireteamSlotSearch = {}));
var FireteamPlatformInviteResult;
(function (FireteamPlatformInviteResult) {
    FireteamPlatformInviteResult[FireteamPlatformInviteResult["None"] = 0] = "None";
    FireteamPlatformInviteResult[FireteamPlatformInviteResult["Success"] = 1] = "Success";
    FireteamPlatformInviteResult[FireteamPlatformInviteResult["AlreadyInFireteam"] = 2] = "AlreadyInFireteam";
    FireteamPlatformInviteResult[FireteamPlatformInviteResult["Throttled"] = 3] = "Throttled";
    FireteamPlatformInviteResult[FireteamPlatformInviteResult["ServiceError"] = 4] = "ServiceError";
})(FireteamPlatformInviteResult = exports.FireteamPlatformInviteResult || (exports.FireteamPlatformInviteResult = {}));
