"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bungie-api-ts
 * Do not edit these files manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * This enum represents a set of flags - use bitwise operators to check which of
 * these match your value.
 */
var IgnoreStatus;
(function (IgnoreStatus) {
    IgnoreStatus[IgnoreStatus["NotIgnored"] = 0] = "NotIgnored";
    IgnoreStatus[IgnoreStatus["IgnoredUser"] = 1] = "IgnoredUser";
    IgnoreStatus[IgnoreStatus["IgnoredGroup"] = 2] = "IgnoredGroup";
    IgnoreStatus[IgnoreStatus["IgnoredByGroup"] = 4] = "IgnoredByGroup";
    IgnoreStatus[IgnoreStatus["IgnoredPost"] = 8] = "IgnoredPost";
    IgnoreStatus[IgnoreStatus["IgnoredTag"] = 16] = "IgnoredTag";
    IgnoreStatus[IgnoreStatus["IgnoredGlobal"] = 32] = "IgnoredGlobal";
})(IgnoreStatus = exports.IgnoreStatus || (exports.IgnoreStatus = {}));
/**
 * Representing external partners to which BNet users can link accounts, but that
 * are not Account System credentials: partnerships that BNet uses exclusively for
 * data.
 */
var PartnershipType;
(function (PartnershipType) {
    PartnershipType[PartnershipType["None"] = 0] = "None";
    PartnershipType[PartnershipType["Twitch"] = 1] = "Twitch";
})(PartnershipType = exports.PartnershipType || (exports.PartnershipType = {}));
