"use strict";
/**
 * Bungie.Net API
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: support@bungie.com
 *
 * NOTE: This class is auto generated by the bungie-api-ts code generator program.
 * https://github.com/DestinyItemManager/bungie-api-ts
 * Do not edit these files manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
/** The known entity types that you can have returned from Trending. */
var TrendingEntryType;
(function (TrendingEntryType) {
    TrendingEntryType[TrendingEntryType["News"] = 0] = "News";
    TrendingEntryType[TrendingEntryType["DestinyItem"] = 1] = "DestinyItem";
    TrendingEntryType[TrendingEntryType["DestinyActivity"] = 2] = "DestinyActivity";
    TrendingEntryType[TrendingEntryType["DestinyRitual"] = 3] = "DestinyRitual";
    TrendingEntryType[TrendingEntryType["SupportArticle"] = 4] = "SupportArticle";
    TrendingEntryType[TrendingEntryType["Creation"] = 5] = "Creation";
    TrendingEntryType[TrendingEntryType["Stream"] = 6] = "Stream";
    TrendingEntryType[TrendingEntryType["Update"] = 7] = "Update";
    TrendingEntryType[TrendingEntryType["Link"] = 8] = "Link";
    TrendingEntryType[TrendingEntryType["ForumTag"] = 9] = "ForumTag";
    TrendingEntryType[TrendingEntryType["Container"] = 10] = "Container";
    TrendingEntryType[TrendingEntryType["Release"] = 11] = "Release";
})(TrendingEntryType = exports.TrendingEntryType || (exports.TrendingEntryType = {}));
